language: scala
jdk: oraclejdk8
scala:
   - 2.11.12

# Build only master and version tags - http://stackoverflow.com/a/31882307/463761
branches:
  only:
    - master
    - /^v[0-9]/

script:
   - sbt ++$TRAVIS_SCALA_VERSION test